#german_lmodified, german_smodified
 # ouput == 1 (in distribution) => biased cls
 biased:
     - Gender:
         operator: '<'
         threshold: 0.0
       class: 0
     - Gender:
         operator: '>='
         threshold: 0.0
       class: 1

 # ODD == 0 => unbiased cls
 unbiased:
     - LoanRateAsPercentOfIncome:
         operator: '<='
         threshold: 0
       class: 1
     - LoanRateAsPercentOfIncome:
         operator: '>'
         threshold: 0
       class: 0
